### ISSUE TITLE
Auto Backup not working!

### ISSUE THREAD

**Issue by s5kufabi** [MirakelX/mirakel-android#599]
Hi!

For me the auto backup mechanism does not seem to work. I am still on version 2.8.2. After a short glance at the source code, I was not even able to find corresponding functions introduced [here](https://github.com/MirakelX/mirakel-android/commit/1fb200ab2182df54b5b4e6944b919905f6de3a68).

If there is any information I can help with, please let me know!

thanks so much!
Fabian

**Comment by azapps** [comment]
Hi,
We have removed that feature because it did not worked correctly before and the database does not corrupt in normal operation mode. Mirakel still makes a backup when upgrading the database.

Best,
Anatolij

**Comment by s5kufabi** [comment]
Hi Anatolij,
thank you for your answear! At least for version 2.8.2 the auto backup feature was still included in the settings. So maybe this should be changed.

thank you for your awesome work on Mirakel!
Fabian
