### ISSUE TITLE
Issues moved back to github ?

### ISSUE THREAD

**Issue by omefire** [MirakelX/mirakel-android#600]
Just a quick question : have the issues been moved back to github ?

**Comment by weiznich** [comment]
Yes

**Comment by omefire** [comment]
Cool. Thanks. Another one : How does one get 'committer' access on the project ?

**Comment by azapps** [comment]
We are using Gerrit to manage the commits and improve our code quality by code review. Here we have a small tutorial how to get started:
https://github.com/MirakelX/mirakel-android/wiki/Development-Tutorial

If you have any development related questions, feel free to join our Gitter Chat: https://gitter.im/MirakelX/mirakel-android

**Comment by omefire** [comment]
Cool, Thanks. I'm planning on working to help improve Mirakel on my free time.
