### ISSUE TITLE
Unable to Import the Project

### ISSUE THREAD

**Issue by Arunkarthicknallasami** [MirakelX/mirakel-android#620]
Hello,
 Im getting this "Error:(64, 0) F:\mirakel-android-master\new_ui\local.properties (The system cannot find the file specified)" While importing project in windows machine, Any idea about the cause?

**Comment by weiznich** [comment]
Copy new_ui/local.properties.dist to new_ui/local.properties.
You also need to copy a few more files. See the development [tutorial](https://github.com/MirakelX/mirakel-android/wiki/Development-Tutorial)

**Comment by Arunkarthicknallasami** [comment]
Thank you, will do that
